export const lineageData = [
  {
    id: 'lakshmandev',
    name: 'Lakshmandev Singh Sharma',
    period: 'Founding Era',
    title: 'Diwan of Jammu & Kashmir',
    biography: 'The founding figure of the Sharma family legacy, Lakshmandev Singh Sharma served as a trusted Munshi and advisor to Maharaja Gulab Singh. In recognition of his unwavering loyalty and exceptional service during the consolidation of rule in Kashmir, he was granted the Diwani of Jammu & Kashmir, equivalent to the Prime Ministership. His administrative acumen and political wisdom established the foundation for generations of family influence in the region.',
  },
  {
    id: 'vidyadhar',
    name: 'Vidyadhar Sharma',
    period: 'Second Generation',
    title: 'Successor to Lakshmandev Singh Sharma',
    biography: 'Vidyadhar Sharma continued the family tradition of administrative service and loyalty to the Dogra rulers. He maintained the family\'s position of influence and contributed to the stability and governance of the region during his tenure.',
  },
  {
    id: 'tirlokchandra',
    name: 'Tirlokchandra Sharma',
    period: 'Third Generation',
    title: 'Administrator and Advisor',
    biography: 'Tirlokchandra Sharma upheld the family\'s legacy of service, providing counsel and administrative expertise during a period of continued development in Jammu & Kashmir. His contributions helped maintain the family\'s standing within the Dogra administration.',
  },
  {
    id: 'pushkarnath',
    name: 'Pushkarnath Sharma',
    period: 'Fourth Generation',
    title: 'Regional Administrator',
    biography: 'Pushkarnath Sharma served during a critical period in the family\'s history, maintaining the traditions of governance and loyalty that characterized the Sharma lineage. His tenure contributed to the family\'s continued prominence in regional affairs.',
  },
  {
    id: 'mangaldas',
    name: 'Mangaldas Sharma',
    period: 'Fifth Generation',
    title: 'Administrator',
    biography: 'Mangaldas Sharma continued the family\'s distinguished record of service, contributing to the administration and stability of the region during his generation. He maintained the family\'s commitment to effective governance and cultural stewardship.',
  },
  {
    id: 'ramdas',
    name: 'Ramdas Sharma',
    period: 'Sixth Generation',
    title: 'Raja of Akhnoor',
    biography: 'Ramdas Sharma served during the period when the family held autonomy over the Akhnoor district. His leadership during this era helped solidify the family\'s role as Rajas of Akhnoor, balancing local governance with loyalty to the Maharaja of Jammu & Kashmir.',
  },
  {
    id: 'gyanchand',
    name: 'Gyanchand Sharma',
    period: 'Seventh Generation',
    title: 'Raja of Akhnoor',
    biography: 'Gyanchand Sharma governed during a period of significant change in the region. His administration focused on maintaining stability and continuing the family\'s traditions of effective governance and cultural patronage.',
  },
  {
    id: 'tilakraj',
    name: 'Tilak Raj Sharma',
    period: 'Eighth Generation',
    title: 'Rawal/Raja - Current Head of the Family',
    biography: 'Rawal/Raja Tilak Raj Singh Sharma serves as the current head of the Sharma family. He has been instrumental in preserving the family\'s heritage and traditions in the post-independence era, ensuring that the legacy of service and cultural stewardship continues into the modern age.',
  },
  {
    id: 'rajkumar',
    name: 'Rajkumar Sharma',
    period: 'Ninth Generation',
    title: 'Kunwar - Designated Successor',
    biography: 'Kunwar Rajkumar Singh Sharma is the designated successor to the family headship. He works alongside his father to preserve the family\'s historical legacy and maintain the traditions that have defined the Sharma family for generations.',
  },
  {
    id: 'aarav',
    name: 'Aarav Sharma',
    period: 'Tenth Generation - Present',
    title: 'Bhanwar - Present Generation',
    biography: 'Bhanwar Aarav Singh Sharma represents the present generation carrying forward the legacy of the Sharma family. As the tenth generation in direct descent from Lakshmandev Singh Sharma, he embodies the continuity of the family\'s heritage and the preservation of its historical significance for future generations.',
  },
];
