export const timelineData = [
  {
    id: 'timeline-1',
    title: 'Service to Maharaja Gulab Singh',
    period: 'Mid-19th Century',
    description: 'Lakshmandev Singh Sharma serves as trusted Munshi and advisor to Maharaja Gulab Singh during the consolidation of rule in Kashmir. His loyalty and administrative expertise prove invaluable during this transformative period.',
    sources: [],
  },
  {
    id: 'timeline-2',
    title: 'Grant of Diwani',
    period: 'Mid-19th Century',
    description: 'In recognition of his exceptional service, Lakshmandev Singh Sharma is granted the Diwani of Jammu & Kashmir, equivalent to the Prime Ministership. This appointment establishes the Sharma family as one of the most influential administrative families in the region.',
    sources: [],
  },
  {
    id: 'timeline-3',
    title: 'Rebellion Under Maharaja Ranveer Singh',
    period: 'Late 19th Century',
    description: 'Maharaja Ranveer Singh faces a rebellion from nobles and military factions. The Sharma family provides crucial support to the Maharaja, helping maintain stability and suppress the uprising.',
    sources: [],
  },
  {
    id: 'timeline-4',
    title: 'Grant of Autonomy Over Akhnoor',
    period: 'Late 19th Century',
    description: 'As a reward for their loyalty during the rebellion, the Sharma family is granted autonomy over the Akhnoor district, becoming the Rajas of Akhnoor while serving under the Maharaja of Jammu & Kashmir.',
    sources: [],
  },
  {
    id: 'timeline-5',
    title: 'Establishment of Administrative Centers',
    period: 'Late 19th - Early 20th Century',
    description: 'Akhnoor Fort is established as the military stronghold, while Amar Mahal Palace serves as the official residence and administrative center of the Sharma family.',
    sources: [],
  },
  {
    id: 'timeline-6',
    title: 'Continued Governance Under Dogra Rule',
    period: 'Early-Mid 20th Century',
    description: 'The Sharma family continues to administer the Akhnoor district, maintaining stability and contributing to the cultural and economic development of the region throughout successive generations.',
    sources: [],
  },
  {
    id: 'timeline-7',
    title: 'Accession to India',
    period: '1947',
    description: 'Maharaja Hari Singh signs the Instrument of Accession, bringing Jammu & Kashmir into the Indian Union. This marks the beginning of significant political and administrative changes for the princely state.',
    sources: [],
  },
  {
    id: 'timeline-8',
    title: 'Abolition of Royal Privileges',
    period: '1947-1971',
    description: 'Formal royal privileges and titles are gradually abolished, culminating in the 26th Amendment to the Indian Constitution in 1971. The Sharma family transitions from formal rulers to private citizens while maintaining their cultural heritage.',
    sources: [],
  },
  {
    id: 'timeline-9',
    title: 'Preservation of Heritage',
    period: 'Late 20th Century - Present',
    description: 'The Sharma family focuses on preserving their historical legacy through documentation, cultural initiatives, and the maintenance of family traditions. The current generation continues to honor the family\'s distinguished history.',
    sources: [],
  },
  {
    id: 'timeline-10',
    title: 'Digital Archive Initiative',
    period: '21st Century',
    description: 'The establishment of this digital heritage archive ensures that the history, lineage, and contributions of the Sharma family remain accessible to future generations, scholars, and researchers interested in the history of Jammu & Kashmir.',
    sources: [],
  },
];
